font_family      Fira Code Regular
italic_font      Fira Code Regular
bold_font        Fira Code Bold
bold_italic_font Fira Code Bold

enable_audio_bell no

background_opacity 1

# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME

